name: LaunchDarkly Integration

on:
  push:
    branches:
      - main
  workflow_dispatch:
  # Add a new event type to trigger the workflow when a LaunchDarkly webhook is received
  repository_dispatch:
    types: [launchdarkly_flag_change]

jobs:
  launchdarkly-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add more steps as needed, such as building and deploying your application

      - name: Trigger deployment
        run: |
          # Your deployment script/command here
          echo "Hello World Main!!"
