name: LaunchDarkly Integration

on:
  repository_dispatch:
    types: [github]

jobs:
  process-event:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Print Event Data
        run: echo "Event type Hello!!"

