name: LaunchDarkly Integration

on: [repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: dispatch trigger
      if: github.event.action == "my_custom_event"
      run: |
        echo "repository_dispatch triggered"
