name: LaunchDarkly Webhook

on:
  push:
    branches:
      - main

jobs:
  launchdarkly-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        if: github.event_name == 'launchdarkly_webhook'
        run: echo "hello world"

      - name: Define Webhook Endpoint
        if: github.event_name == 'launchdarkly_webhook'
        run: |
          # Define a simple HTTP server using Python
          echo "hello world endpoint"
